### ISSUE TITLE
How to write an example that uses elm/bytes ?

### ISSUE THREAD

**Issue by romariolopezc** [stoeffel/elm-verify-examples#80]
```elm
encode (unsignedInt8     7)
--> <1 bytes> : Bytes
```

Example: https://package.elm-lang.org/packages/elm/bytes/latest/Bytes-Encode#encode

Error:
```
Something went wrong while parsing an expression (in parentheses) in spec0's
definition.

25|                 (
26|                 <1 bytes>
                    ^
I was expecting to see an expression, like x or 42.
```

**Comment by stoeffel** [comment]
What are you trying to verify? I assume there is a function you would like to verify, can you share some more context?

My answer to that specific error:
The problem here is that verified example need to be valid Elm on both sides of `-->`.
`<1 bytes> : Bytes` isn't valid Elm. Since `Bytes` is an [opaque type](https://medium.com/@ckoster22/advanced-types-in-elm-opaque-types-ec5ec3b84ed2) there is not much you can do except for decoding it again.
As an example:
```elm
    import Bytes.Encode as Encode
    import Bytes.Decode as Decode

    Encode.encode (Encode.unsignedInt8 7)
        |> Decode.decode Decode.unsignedInt8
    --> Just 7
```

@romariolopezc Does this help or do you have more questions?

**Comment by romariolopezc** [comment]
Ohh okok, I get it now. Thank you for the help

**Comment by stoeffel** [comment]
Cool! Let me know if there is something else I can help you with.
